### ISSUE TITLE
NumberFormatException when create hologram

### ISSUE THREAD

**Issue by FoviOX** [VolmitSoftware/Gloss#84] opened 2019-08-04 12:21 UTC
Error when create hologram.
https://pastebin.com/xuTXFHx3
Gloss v1.3.1
GlossChatBubbles v1.2.0
Mortar v1.0.71
Spigot 1.12.2

Video:
(Click on image to see video)
<div align="left">
  <a href="https://www.youtube.com/watch?v=7W4yZy-iTaQ"><img src="https://img.youtube.com/vi/7W4yZy-iTaQ/0.jpg" alt="Click to see video"></a>
</div>

**Comment by DavidRockin** [comment] 2019-08-06 19:19
That is some beautiful console spam, I'll look into it.

**Comment by Andre601** [comment] 2019-08-18 20:07
`java.lang.NumberFormatException: For input string: "-0,0658"`
There is a comma instead of a dot... You need to use dots to set the number properly.

Commas are used to separate a 1k+ number. F.e. 1100 -> 1,100

![image](https://user-images.githubusercontent.com/11576465/63229791-8a739880-c204-11e9-8acb-37067ec46c88.png)

**Comment by DavidRockin** [comment] 2019-08-18 21:06
I have a second confirmation of this issue, but they're on Windows. But I cannot reproduce it. It might be a Windows-related issue?

@Andre601 If you look at the video, OP opens the hologram file. None of the coords are formatted to use commas.

**Comment by DavidRockin** [comment] 2019-08-18 21:12
Tracked the issue down. Going to change the logic when rounding locations.

**Comment by DavidRockin** [comment] 2019-08-18 22:54
This should be fixed in 1.3.2. I'll close this for now. If this persists, please reopen this issue.

**Closed as completed by DavidRockin** 2019-08-18 22:54 UTC
Labels: bug, IN-PROGRESS
