### ISSUE TITLE
Error while stopping/reloading Gloss [1.13.2]

### ISSUE THREAD

**Issue by lucas2107** [VolmitSoftware/Gloss#69] opened 2019-04-15 13:49 UTC
Here's the error: https://pastebin.com/TrPHULCA

**Comment by DavidRockin** [comment] 2019-07-18 21:12
Duplicate of https://github.com/VolmitSoftware/Mortar/issues/8, it has been fixed. Mortar 1.0.70 will be deploying soon.

**Closed by DavidRockin** 2019-07-18 21:12 UTC
