### ISSUE TITLE
Special characters like 'ä ö ü' getting replaced with '?'

### ISSUE THREAD

**Issue by bytemedavis** [VolmitSoftware/Gloss#87] opened 2019-08-16 22:57 UTC
**Describe the bug**
When creating holograms, characters like 'ä, ö, ü' get displayed correctly but after restarting the server they get replaced with ?.

**To Reproduce**
1. Create a holo, use a special character like the ones above
2. Have a look at them, watch them work
3. Restart server
4. Have a look at them, watch them being replaced with ?

**Expected behavior**
Not to get replaced lmao

**Screenshots or Video Recordings**
https://i.imgur.com/jKS8IJr.png
https://i.imgur.com/QiVPNmz.png
https://i.imgur.com/Gx1N8fK.png

**Server and Plugin Informations**
 - Installed plugins: -
 - Gloss and Mortar Version: Gloss 1.3.1, Mortar v1.0.71
 - Server Platform and Version [eg: PaperSpigot 1.14.4]: Paper 1.14.4 build 167
 - Operating System (if applicable): Linux (using deploys.io as host)

**Comment by Andre601** [comment] 2019-08-16 23:11
I personally wouldn't use ö, ä, ü, etc. in hologram names to begin with...
But it looks like Gloss doesn't save the JSON files as UTF-8 encoded? Like do the lines in the files also have ? and did you try to change it and save that?

**Comment by DavidRockin** [comment] 2019-08-17 00:43
@Andre601 Most modern file systems should support non-ascii characters in file and directory names. So it really shouldn't be a problem. Although with the exception of Windows being really hacky and still continuing to use [legacy DOS naming conventions from the 80's](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file)

@bytemedavis  Back to the issue. I actually can't seem to reproduce this issue? I've named the hologram containing UTF8 characters and the hologram contains UTF8 characters as well. This is a bit strange. Does the issue persist if you use UTF-8 characters in the MOTD, board and tablist? Or is this strictly a hologram related issue?

How are you editing your holograms? Are you editing in game via `/holo edit` or are you editing in the config and reloading (or booting) your server?

Can you copy your server files and run them locally on your system, and check if this issue persists?

**Comment by bytemedavis** [comment] 2019-08-17 16:26
@DavidRockin I am editing the holograms through /holo edit. I have this issue with no other plugin so far, even my own plugins use the correct encoding for this. I don't know if this matters, but I am using deploys.io as hosting and they use pterodactyl as their panel.

**Comment by DavidRockin** [comment] 2019-08-17 16:27
If you run the server locally, does this issue persist?

**Comment by bytemedavis** [comment] 2019-08-17 17:03
@DavidRockin It works on my local server, even tho there's this error spamming the console that got reported already by someone else (NumberFormatException). What should I do then?

**Comment by DavidRockin** [comment] 2019-08-18 19:56
Possibly related, image provided by OP
https://i.imgur.com/4acaHWv.png

**Comment by DavidRockin** [comment] 2019-08-18 21:14
Fixed in 1.3.2, thanks for the help!

**Closed as completed by DavidRockin** 2019-08-18 21:14 UTC
Labels: bug, IN-PROGRESS

**Comment by bytemedavis** [comment] 2019-08-19 02:33
no worries!
